# Generated by Django 5.1.5 on 2025-01-25 12:14

import apps.profiles.models
import django.db.models.deletion
import django_enumfield.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        blank=True,
                        default="media/default/default.png",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=128, null=True)),
                ("last_name", models.CharField(blank=True, max_length=128, null=True)),
                ("profession", models.CharField(blank=True, max_length=128, null=True)),
                ("location", models.CharField(blank=True, max_length=128, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "gender",
                    django_enumfield.db.fields.EnumField(
                        default=0, enum=apps.profiles.models.Gender
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "profiles",
                "db_table": "profiles",
                "ordering": ["id", "user"],
            },
        ),
    ]
