# Generated by Django 5.1 on 2024-10-13 15:36

import apps.profiles.models
import django_enumfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=django_enumfield.db.fields.EnumField(
                default=3, enum=apps.profiles.models.Gender
            ),
        ),
    ]
