# Generated by Django 5.1 on 2024-09-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="user_<built-in function id>.jpg", upload_to="profile_images"
            ),
        ),
    ]
