version: '3.9'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: trackmate-web
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - trackmate
    restart: always

  db:
    image: postgres:16
    container_name: trackmate-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      - trackmate
    restart: always

volumes:
  postgres_data:

networks:
  trackmate: