services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: trackmate-web
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - trackmate-net
    restart: always

  postgres:
    image: postgres:16
    container_name: trackmate-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-h", "${POSTGRES_HOST}", "-p", "${POSTGRES_PORT}"]
    ports:
      - "5433:5432"
    networks:
      - trackmate-net
    restart: always

volumes:
  postgres_data:

networks:
  trackmate-net: