# Generated by Django 5.1 on 2024-10-13 15:35

import apps.tasks.models
import django.utils.timezone
import django_enumfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_by",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=django_enumfield.db.fields.EnumField(
                default=2, enum=apps.tasks.models.Priority
            ),
        ),
    ]
