# Generated by Django 5.1 on 2024-08-25 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="сreated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
