# Generated by Django 5.1 on 2024-08-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_сreated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="сreated_at",
            new_name="created_at",
        ),
    ]
